name: Continuous integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      extensions: intl, mbstring, xdebug

    strategy:
      matrix:
        php-version:
          - "5.3"
          - "5.4"
          - "5.5"
          - "5.6"
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"

    steps:
      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          extensions: "${{ env.extensions }}"
          ini-values: "memory_limit=-1, error_reporting=E_ALL, display_errors=On"
          coverage: xdebug
          tools: composer
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download dependencies
        run: composer update --no-interaction --no-progress
      - name: Run tests
        run: vendor/bin/phpunit
